name: SwapBid
version: "0.2.1"
slug: swap_bid
description: Umgekehrter Kleinanzeigenmarkt – Geld posten, andere bieten Objekte dafür
url: "https://github.com/GianlucaKo95/swap-bid"
image: "ghcr.io/gianlucako95/swap-bid"
arch:
  - amd64
  - aarch64
  - armv7
init: false
startup: application
boot: auto
ports:
  3045/tcp: 3045
ports_description:
  3045/tcp: SwapBid Web-UI
webui: "http://[HOST]:[PORT:3045]"
options:
  supabase_url: ""
  supabase_anon_key: ""
schema:
  supabase_url: url
  supabase_anon_key: str
